Repository UFLX2MuMu/Ntupliser, pull requests merged in 2019-10, with the labels that each got.

#87 Issue 86 add fsr phot collection 2017
  DiMuons/interface/PhotHelper.h
  DiMuons/interface/PhotInfo.h
  DiMuons/plugins/UFDiMuonsAnalyzer.cc
  DiMuons/plugins/UFDiMuonsAnalyzer.h
  DiMuons/python/Analyzer_MC_cff.py
  DiMuons/python/Analyzer_cff.py
  DiMuons/src/PhotHelper.cc
Labels: 2017

#88 Issue 84 kinfit phi d0 etc 2016
  DiMuons/interface/MuPairHelper.h
  DiMuons/interface/MuonInfo.h
  DiMuons/src/MuPairHelper.cc
  DiMuons/src/MuonHelper.cc
Labels: 2016, enhancement

#90 Porting minor dev from prod-v18.1.X
  DiMuons/crab/make_crab_script.py
  DiMuons/python/Samples.py
Labels: 2018, enhancement, minor
